skip_tags: true

os: Visual Studio 2015

environment:
  matrix:
{%- if cookiecutter.earliest_supported_python <= "3.5" %}
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
{%- endif %}
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build_script:
  - "git --no-pager log -n2"
  - "echo %APPVEYOR_REPO_COMMIT%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install ."
  - "pip install -Ur ci/test-requirements.txt"
  - "pip install codecov"

test_script:
  - "mkdir empty"
  - "cd empty"
  # Make sure it's being imported from where we expect
  - "python -c \"import os, {{cookiecutter.package_name}}; print(os.path.dirname({{cookiecutter.package_name}}.__file__))\""
  - "python -u -m pytest -W error -ra -v -s --pyargs {{cookiecutter.package_name}} --cov={{cookiecutter.package_name}} --cov-config=../.coveragerc"
  - "codecov"
